[features]
seeds = false
[programs.localnet]
twitter_program = "4u1pQBd6oZHYGHqHeyb9b3hW1XGeiz2msD7qiTcedNuP"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/nikhil/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
